# Generated by Django 5.1 on 2024-08-16 10:50

import apps.bot.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('admins', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None, validators=[apps.bot.models.validate_unique_array], verbose_name='Admins')),
                ('secret_key', models.CharField(max_length=255, verbose_name='Secret key')),
                ('bot_url', models.URLField(max_length=255, verbose_name='Bot URL')),
            ],
            options={
                'verbose_name': 'Telegram bot configuration',
                'verbose_name_plural': 'Telegram bot configuration',
            },
        ),
    ]
