# Generated by Django 5.1 on 2024-08-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambotconfiguration',
            name='bot_url',
            field=models.URLField(default='https://t.me/learning_njrBot', max_length=255, verbose_name='Bot URL'),
        ),
        migrations.AlterField(
            model_name='telegrambotconfiguration',
            name='secret_key',
            field=models.CharField(default='secret_key', max_length=255, verbose_name='Secret key'),
        ),
        migrations.AlterField(
            model_name='telegrambotconfiguration',
            name='token',
            field=models.CharField(default='5706572197:AAHvVB1DQhlHSDI9kxuriZzpPUq8slsjrH8', max_length=255, verbose_name='Token'),
        ),
    ]
